### ISSUE TITLE
Test Chewie with mocking and calls to the individual message consuming/producing methods

### ISSUE THREAD

**Issue by samrussell** [faucetsdn/chewie#70]
#69 gets rid of the threads from the tests, next step is to totally mock out eventlet here.

I had a bit of a play and couldn't quite get it done (the way coroutines are declared in python is weird but eventlet/gevent/asyncio figure out how to do this), but what we need is basically to build our own hub with no scheduler, and have a method to step forward and bump everything once. We'll need to mock the calls to sleep and queue read etc so that they don't block, and ultimately we can step them forward until they're waiting on queues and then make the tests look like get_to_block -> add_message_to_queue -> step_forward -> assert_output

**Comment by samrussell** [comment]
I've looked into this further, coroutines seem to be the asyncio way of doing things and what we probably need is a subclass of eventlet.Hub with a custom on-demand scheduler

**Comment by byllyfish** [comment]
I'm not quite sure if this is relevant or useful, but I have an asyncio port here: https://github.com/byllyfish/chewie/tree/asyncio_next

This port does not use eventlet, and it appears to pass all the tests.

**Comment by byllyfish** [comment]
For the most part, the core state machine is already agnostic with respect to eventlet/asyncio. The one difference is to use `queue.put_nowait` instead of `queue.put`. `put` blocks if there is no room in the queue, but chewie uses unbounded queues so it will never block. `put_nowait` never blocks but raises an exception if there is no room in the queue.

 I can submit a PR that changes `put` to `put_nowait`.  The queue API's are identical between stdlib, eventlet, and asyncio, so using put_nowait shouldn't break anything.

I have a port of Faucet to asyncio (replacing ryu) that passes all the integration tests, including the 8021x ones using the asyncio chewie (0.0.9) code. Tag a new version when you are ready, and I'll re-rerun the faucet tests with the new asyncio code.

**Comment by samrussell** [comment]
This sounds good, I've opened #83 to carry on this discussion but the short answer is yes, changing `put` to `put_nowait` seems like the correct thing to do regardless of where we go after that

**Comment by samrussell** [comment]
#86 delivers the key piece of this, a little tidy up from there and we're all sorted
